"""SIC code to industry name mapping for SEC filings."""

SIC_MAP = {
    "1000": "Metal Mining",
    "1040": "Gold Mining",
    "1311": "Crude Petroleum & Natural Gas",
    "1381": "Drilling Oil & Gas Wells",
    "1382": "Oil & Gas Field Services",
    "2000": "Food & Kindred Products",
    "2011": "Meat Packing Plants",
    "2013": "Sausages & Other Prepared Meats",
    "2020": "Dairy Products",
    "2030": "Canned & Preserved Fruits/Vegetables",
    "2040": "Grain Mill Products",
    "2050": "Bakery Products",
    "2060": "Sugar & Confectionery Products",
    "2080": "Beverages",
    "2090": "Food Preparations & Kindred Products",
    "2100": "Tobacco Products",
    "2200": "Textile Mill Products",
    "2300": "Apparel & Other Finished Products",
    "2400": "Lumber & Wood Products",
    "2500": "Furniture & Fixtures",
    "2510": "Household Furniture",
    "2520": "Office Furniture",
    "2522": "Office Furniture (Except Wood)",
    "2600": "Paper & Allied Products",
    "2611": "Pulp Mills",
    "2621": "Paper Mills",
    "2670": "Converted Paper & Paperboard Products",
    "2700": "Printing, Publishing & Allied Industries",
    "2800": "Chemicals & Allied Products",
    "2810": "Industrial Chemicals & Synthetics",
    "2820": "Plastics & Synthetic Materials",
    "2821": "Plastics Materials & Resins",
    "2834": "Pharmaceutical Preparations",
    "2835": "In Vitro & In Vivo Diagnostics",
    "2836": "Biological Products",
    "2840": "Soap, Detergents & Cleaning Products",
    "2842": "Specialty Cleaning & Polishing Products",
    "2844": "Perfumes, Cosmetics & Toilet Preparations",
    "2860": "Industrial Chemicals",
    "2891": "Adhesives & Sealants",
    "2911": "Petroleum Refining",
    "2950": "Asphalt Paving & Roofing Materials",
    "2990": "Petroleum & Coal Products",
    "3060": "Rubber & Plastics Hose & Belting",
    "3080": "Plastics Products",
    "3089": "Plastics Products, NEC",
    "3100": "Leather & Leather Products",
    "3312": "Steel Works & Blast Furnaces",
    "3317": "Steel Pipe & Tubes",
    "3350": "Rolling & Drawing of Nonferrous Metals",
    "3411": "Metal Cans",
    "3420": "Cutlery, Handtools & General Hardware",
    "3440": "Fabricated Structural Metal",
    "3460": "Metal Forgings & Stampings",
    "3480": "Ordnance & Accessories",
    "3510": "Engines & Turbines",
    "3523": "Farm Machinery & Equipment",
    "3524": "Lawn & Garden Tractors & Equipment",
    "3530": "Construction & Mining Equipment",
    "3533": "Oil & Gas Field Machinery & Equipment",
    "3540": "Metalworking Machinery & Equipment",
    "3550": "Special Industry Machinery",
    "3559": "Special Industry Machinery, NEC",
    "3560": "General Industrial Machinery & Equipment",
    "3561": "Pumps & Pumping Equipment",
    "3562": "Ball & Roller Bearings",
    "3569": "General Industrial Machinery, NEC",
    "3570": "Computer & Office Equipment",
    "3572": "Computer Storage Devices",
    "3576": "Computer Communications Equipment",
    "3577": "Computer Peripheral Equipment",
    "3579": "Office Machines, NEC",
    "3580": "Refrigeration & Service Industry Machinery",
    "3585": "Air-Conditioning & Heating Equipment",
    "3590": "Miscellaneous Industrial Machinery",
    "3600": "Electronic & Other Electrical Equipment",
    "3612": "Power, Distribution & Specialty Transformers",
    "3621": "Motors & Generators",
    "3630": "Household Appliances",
    "3634": "Housewares & Fans",
    "3640": "Electric Lighting & Wiring Equipment",
    "3651": "Household Audio & Video Equipment",
    "3661": "Telephone & Telegraph Apparatus",
    "3669": "Communications Equipment, NEC",
    "3670": "Electronic Components & Accessories",
    "3672": "Printed Circuit Boards",
    "3674": "Semiconductors & Related Devices",
    "3678": "Electronic Connectors",
    "3679": "Electronic Components, NEC",
    "3690": "Electrical Industrial Apparatus, NEC",
    "3711": "Motor Vehicles & Passenger Car Bodies",
    "3713": "Truck Trailers",
    "3714": "Motor Vehicle Parts & Accessories",
    "3720": "Aircraft & Parts",
    "3721": "Aircraft",
    "3724": "Aircraft Engines & Engine Parts",
    "3728": "Aircraft Parts & Auxiliary Equipment",
    "3730": "Ship & Boat Building & Repairing",
    "3743": "Railroad Equipment",
    "3760": "Guided Missiles & Space Vehicles",
    "3812": "Defense Electronics & Communications",
    "3822": "Environmental Controls",
    "3825": "Instruments for Measuring",
    "3826": "Laboratory Analytical Instruments",
    "3827": "Optical Instruments & Lenses",
    "3829": "Measuring & Controlling Devices, NEC",
    "3841": "Surgical & Medical Instruments",
    "3842": "Orthopedic, Prosthetic & Surgical Appliances",
    "3844": "X-Ray Apparatus & Tubes",
    "3845": "Electromedical & Therapeutic Apparatus",
    "3861": "Photographic Equipment & Supplies",
    "3900": "Miscellaneous Manufacturing",
    "3944": "Games, Toys & Children's Vehicles",
    "3990": "Miscellaneous Manufacturing Industries",
    "4011": "Railroads — Line-Haul Operating",
    "4013": "Railroad Switching & Terminal Establishments",
    "4100": "Local & Suburban Transit",
    "4210": "Trucking & Courier Services",
    "4213": "Trucking (Except Local)",
    "4400": "Water Transportation",
    "4412": "Deep Sea Foreign Transportation of Freight",
    "4512": "Air Transportation — Scheduled",
    "4513": "Air Courier Services",
    "4522": "Air Transportation — Nonscheduled",
    "4581": "Airports, Flying Fields & Airport Services",
    "4610": "Pipe Lines (No Natural Gas)",
    "4700": "Transportation Services",
    "4731": "Freight Transportation Arrangement",
    "4812": "Radiotelephone Communications",
    "4813": "Telephone Communications",
    "4822": "Telegraph & Other Message Communications",
    "4832": "Radio Broadcasting Stations",
    "4833": "Television Broadcasting Stations",
    "4841": "Cable & Other Pay Television Services",
    "4899": "Communications Services, NEC",
    "4900": "Electric, Gas & Sanitary Services",
    "4911": "Electric Services",
    "4922": "Natural Gas Distribution",
    "4923": "Natural Gas Transmission & Distribution",
    "4924": "Natural Gas Distribution",
    "4931": "Electric & Other Services Combined",
    "4932": "Gas & Other Services Combined",
    "4941": "Water Supply",
    "4950": "Sanitary Services",
    "4953": "Refuse Systems",
    "4955": "Hazardous Waste Management",
    "5000": "Durable Goods — Wholesale",
    "5010": "Motor Vehicles & Motor Vehicle Parts",
    "5013": "Motor Vehicle Supplies & New Parts",
    "5040": "Professional & Commercial Equipment",
    "5045": "Computers & Peripherals",
    "5047": "Medical & Hospital Equipment & Supplies",
    "5050": "Metals & Minerals",
    "5051": "Metals Service Centers & Offices",
    "5060": "Electrical Apparatus & Equipment",
    "5065": "Electronic Parts & Equipment",
    "5080": "Industrial & Personal Service Paper",
    "5084": "Industrial Machinery & Equipment",
    "5090": "Durable Goods, NEC",
    "5110": "Paper & Paper Products",
    "5122": "Drugs, Drug Proprietaries & Sundries",
    "5140": "Groceries & Related Products",
    "5141": "Groceries — General Line",
    "5160": "Chemicals & Allied Products",
    "5169": "Chemicals & Allied Products, NEC",
    "5171": "Petroleum & Products (Wholesale)",
    "5172": "Petroleum Products (Wholesale)",
    "5190": "Nondurable Goods, NEC",
    "5200": "Building Materials & Garden Supplies",
    "5211": "Lumber & Building Materials Dealers",
    "5251": "Hardware Stores",
    "5311": "Department Stores",
    "5331": "Variety Stores",
    "5399": "General Merchandise Stores, NEC",
    "5411": "Grocery Stores",
    "5412": "Convenience Stores",
    "5500": "Auto Dealers & Gas Stations",
    "5531": "Auto & Home Supply Stores",
    "5600": "Apparel & Accessory Stores",
    "5621": "Women's Clothing Stores",
    "5651": "Family Clothing Stores",
    "5700": "Home Furniture & Equipment Stores",
    "5712": "Furniture Stores",
    "5731": "Radio, TV & Consumer Electronics Stores",
    "5812": "Eating Places",
    "5900": "Retail Stores, NEC",
    "5912": "Drug Stores & Proprietary Stores",
    "5940": "Sporting Goods & Hobby Stores",
    "5944": "Jewelry Stores",
    "5945": "Hobby, Toy & Game Shops",
    "5961": "Catalog & Mail-Order Houses",
    "5990": "Retail Stores, NEC",
    "6020": "Savings Institutions — Federally Chartered",
    "6021": "National Commercial Banks",
    "6022": "State Commercial Banks",
    "6035": "Savings Institutions — Federally Chartered",
    "6036": "Savings Institutions — Not Federally Chartered",
    "6099": "Services Allied With Banking",
    "6111": "Federal & Federally-Sponsored Credit Agencies",
    "6120": "Savings Institutions",
    "6141": "Personal Credit Institutions",
    "6153": "Short-Term Business Credit Institutions",
    "6159": "Federal-Sponsored Credit Agencies, NEC",
    "6162": "Mortgage Bankers & Loan Correspondents",
    "6163": "Loan Brokers",
    "6199": "Finance Services",
    "6200": "Security & Commodity Services",
    "6211": "Security Brokers, Dealers & Flotation",
    "6282": "Investment Advice",
    "6311": "Life Insurance",
    "6321": "Accident & Health Insurance",
    "6324": "Hospital & Medical Service Plans",
    "6331": "Fire, Marine & Casualty Insurance",
    "6399": "Insurance Carriers, NEC",
    "6411": "Insurance Agents, Brokers & Service",
    "6500": "Real Estate",
    "6510": "Real Estate Operators & Lessors",
    "6512": "Operators of Apartment Buildings",
    "6552": "Land Subdividers & Developers",
    "6726": "Investment Offices, NEC",
    "6770": "Blank Checks",
    "6798": "Real Estate Investment Trusts",
    "7011": "Hotels & Motels",
    "7200": "Personal Services",
    "7310": "Services — Advertising",
    "7311": "Advertising Services",
    "7312": "Outdoor Advertising Services",
    "7320": "Services — Consumer Credit Reporting",
    "7331": "Mailing, Reproduction & Stenographic Services",
    "7340": "Services — To Buildings & Dwellings",
    "7350": "Miscellaneous Equipment Rental & Leasing",
    "7359": "Equipment Rental & Leasing, NEC",
    "7361": "Help Supply Services",
    "7363": "Help Supply Services",
    "7370": "Computer Programming & Data Processing",
    "7371": "Computer Programming Services",
    "7372": "Prepackaged Software",
    "7374": "Computer Processing & Data Preparation",
    "7380": "Miscellaneous Business Services, NEC",
    "7389": "Services — Misc Business Services, NEC",
    "7500": "Automotive Repair, Services & Parking",
    "7510": "Automotive Rental & Leasing",
    "7812": "Motion Picture & Tape Distribution",
    "7819": "Services Allied to Motion Picture Production",
    "7900": "Amusement & Recreation Services",
    "7941": "Professional Sports Clubs",
    "7990": "Amusement & Recreation Services, NEC",
    "7997": "Membership Sports & Recreation Clubs",
    "8000": "Health Services",
    "8011": "Offices & Clinics of Doctors of Medicine",
    "8042": "Offices & Clinics of Optometrists",
    "8050": "Skilled Nursing Care Facilities",
    "8051": "Skilled Nursing Care Facilities",
    "8060": "Hospitals",
    "8062": "General Medical & Surgical Hospitals",
    "8071": "Health Services",
    "8082": "Home Health Care Services",
    "8090": "Health Services, NEC",
    "8200": "Educational Services",
    "8700": "Engineering, Accounting & Research Services",
    "8711": "Engineering Services",
    "8731": "Commercial Physical & Biological Research",
    "8741": "Management Services",
    "8742": "Management Consulting Services",
    "8744": "Facilities Support Management Services",
    "8900": "Services, NEC",
    "9995": "Non-Operating Establishments",
}


def normalize_sector(raw: str) -> str:
    """Normalize sector field: map bare SIC codes to 'Code - Name' format."""
    if not raw or raw == "Unknown":
        return "Unknown"

    raw = raw.strip()

    # Already has a descriptive name with code (e.g., "SEMICONDUCTORS & RELATED DEVICES [3674]")
    # or is a multi-word name -- keep as-is but clean up
    if raw.isdigit():
        name = SIC_MAP.get(raw, None)
        if name:
            return f"{raw} - {name}"
        return f"{raw} - Industry Code {raw}"

    # Check if it's a code with brackets like "3674"
    # Some have format "CODE - Name" already
    if " - " in raw and raw.split(" - ")[0].strip().isdigit():
        return raw  # already good

    # It's a text description (e.g., "SEMICONDUCTORS & RELATED DEVICES")
    # Try to find matching SIC code
    raw_upper = raw.upper()
    for code, name in SIC_MAP.items():
        if name.upper() == raw_upper or raw_upper in name.upper() or name.upper() in raw_upper:
            return f"{code} - {name}"

    # Return as-is if it's a descriptive name
    return raw
