[server]
headless = true
port = 8501

[theme]
primaryColor = "#CD1515"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#333333"
font = "sans serif"

[browser]
gatherUsageStats = false
